### PR TITLE
Port to v8

### PR DESCRIPTION
**Pull request by skttl**
Started working on porting to v8.

Don't know the right approach to doing it, but here is an update for the main project, which makes it build on v8.

Still needs some angular work though :) Seems like there is changes in the way it handles localization, some styling, and most of all the dialogService is gone.

billede

### CODE REVIEW

**Comment by abjerner** [comment]
@skttl Thanks a lot. This is awesome 👍

I actually started porting this myself, but got stuck as the v8 codebase kept changing and wasn't very well documented (this was back in January). It seems that you have made more progress than me, so let's just continue with your PR 😉

I'll try to find some time to look at your code, and report back. I've skimmed through your code, and I think everything looks good (as far as I can tell - I'm not fully up to date on V8 yet).

I see you've changed the assembly name to `Skybrud.Umbraco.Redirects8`. Is this because you believe it should be released as a separate NuGet/Umbraco package for V8? I'm a bit unsure myself what would be the right approach, so any feedback on this would be great.

**Comment by skttl** [comment]
No that was just because I copied the project, so I could have the original
by the side. I thought I had changed all the Redirects8 names back 🙂

I'm not sure what the best approach is. If the v7 package is going to be
continued, there will be some double work down the line.

søn. 3. mar. 2019 16.35 skrev Anders Bjerner <notifications@github.com>:

**Comment by abjerner** [comment]
Hi @skttl,

What's the status of your PR? I've started actively looking at porting this package to Umbraco, and seeing as this PR is still marked as a draft, I'd just wanted to check back for a status.

Should I just merge it regardless of the draft label, and base my work on that? (I think your changes looks good)

**Comment by skttl** [comment]
Hi @abjerner 

Haven't been able to do much, but I just pushed a change where it uses the editorService in stead of the dialogService. IIRC it should work now - but of course needs some polish.

Feel free to base your work on it, I'm probably not going to do more in the coming weeks anyway :)

Let me know if you need any help!

**Comment by abjerner** [comment]
@skttl awesome 👍 

I'm in the process of converting some of our packages to V8, so this one is next one my list. But with Codegarden coming up, I'm probably not going to do much progress this week either.

**Pull request merged**
