### PR TITLE
added the ability to raise an event when a redirect is served

### PR DESCRIPTION
**Pull request by prjseal**
We spoke about this recently. I need to add this functionality for a client and I said I would do a PR.

- added the ability to raise an event when a redirect is served
- added a migration to add a last used date column so we can hook into the new redirect served event and update the last used date at an interval which suits our use case
- added a method in the redirect service to update the last used date when called
- changed the scope of the redirect service to singleton to allow for events to work. It seems safe to do this as you are newing up the scope for the database each time anyway.

With the event being raised and the last used date in the table, we can now hook into the redirect served event and update the last used date for that redirect at an interval that suits our implementation by using a composer/component like this in our project:

```cs
using System;
using System.Configuration;
using Skybrud.Umbraco.Redirects.Composers;
using Skybrud.Umbraco.Redirects.Events;
using Skybrud.Umbraco.Redirects.Models;
using Umbraco.Core;
using Umbraco.Core.Composing;

namespace TestHarness.Composing
{
    [ComposeAfter(typeof(RedirectsComposer))]
    [RuntimeLevel(MinLevel = RuntimeLevel.Run)]
    public class RedirectEventsComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            if (!int.TryParse(ConfigurationManager.AppSettings["SkybrudRedirects:LastUsedUpdatePeriodInDays"], out var updatePeriodInDays)) return;

            composition.Components().Append<RedirectEventsComponent>();
        }

    }

    public class RedirectEventsComponent : IComponent
    {
        private readonly IRedirectsService _redirectsService;

        public RedirectEventsComponent(IRedirectsService redirectsService)
        {
            _redirectsService = redirectsService;
        }

        public void Initialize()
        {
            _redirectsService.RedirectServed += RedirectsService_RedirectServed;
        }

        private void RedirectsService_RedirectServed(object sender, RedirectServedEventArgs e)
        {
            var redirect = e.Redirect;

            if (!int.TryParse(ConfigurationManager.AppSettings["SkybrudRedirects:LastUsedUpdatePeriodInDays"], out var updatePeriodInDays)) return;

            if (redirect.LastUsed == null)
            {
                _redirectsService.UpdateLastUsedDate(redirect);
            }
            else
            {
                var daysSinceLastUsed = (DateTime.UtcNow - redirect.LastUsed.Value).TotalDays;
                if (daysSinceLastUsed >= updatePeriodInDays)
                {
                    _redirectsService.UpdateLastUsedDate(redirect);
                }
            }
        }

        public void Terminate()
        {

        }
    }
}

```

Depending on the site you could also hook into the event to keep a count of how many times the redirect is used etc.

Let me know what you think of this PR and if there is anything you need me to change before you can merge it, if at all.

### CODE REVIEW

**Comment by abjerner** [comment]
Hi @prjseal,

Thank for creating this PR 👍 

I had a chat with a colleague, and we'd prefer to not have the logic for the last used date included directly in the package. As there are different ways to go about this, we'd think this this should be up to developers to handle. For instance, other may want to log each time a redirect is accessed, rather than just the last time it's accessed.

For the events part, I think there should ideally be **PreLookup** and **PostLookup** events. The **PreLookup** event could then be used before the package is hitting the database, letting developers set their own redirect. And **PostLookup**, which is probably equal to your **RedirectServed** event, can then be used to do something after the package has hit the database.

To improve the usability of the events, I think the event args should also include a reference to the current HTTP context. So something like:

```csharp
public class RedirectPostLookupEventArgs : EventArgs {

    public HttpContextBase HttpContext { get; }
    
    public RedirectItem Redirect { get; set; }

    public RedirectPostLookupEventArgs(HttpContext context, RedirectItem redirect) {
        HttpContext = new HttpContextWrapper(context);
        Redirect = redirect;
    } 

}
```
If you can work apply these changes, I'd be happy to merge your PR 😉

**Comment by prjseal** [comment]
Hi @abjerner 

That's great. I'll make these changes next week and update the PR. 

Kind regards 

Paul

**Comment by prjseal** [comment]
@abjerner I have made the changes you requested. Hopefully that is enough for you to merge it now.

**Comment by prjseal** [comment]
This code will create a log entry for the prelookup and postlookup events:

```cs
using Skybrud.Umbraco.Redirects.Composers;
using Skybrud.Umbraco.Redirects.Events;
using Skybrud.Umbraco.Redirects.Models;
using Umbraco.Core;
using Umbraco.Core.Composing;
using Umbraco.Core.Logging;

namespace TestHarness.Composing
{
    [ComposeAfter(typeof(RedirectsComposer))]
    [RuntimeLevel(MinLevel = RuntimeLevel.Run)]
    public class RedirectEventsComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            composition.Components().Append<RedirectEventsComponent>();
        }

    }

    public class RedirectEventsComponent : IComponent
    {
        private readonly IRedirectsService _redirectsService;
        private readonly ILogger _logger;

        public RedirectEventsComponent(IRedirectsService redirectsService, ILogger logger)
        {
            _redirectsService = redirectsService;
            _logger = logger;
        }

        public void Initialize()
        {
            _redirectsService.PreLookup += RedirectsService_PreLookup;
            _redirectsService.PostLookup += RedirectsService_PostLookup;
        }

        private void RedirectsService_PreLookup(object sender, RedirectPreLookupEventArgs e)
        {
            var rawUrl = e.RawUrl;

            _logger.Info(typeof(RedirectEventsComponent), "Redirect Pre Lookup. Url: " + rawUrl);
        }

        private void RedirectsService_PostLookup(object sender, RedirectPostLookupEventArgs e)
        {
            var redirect = e.Redirect;

            _logger.Info(typeof(RedirectEventsComponent), "Redirect Post Lookup. From: " + redirect.Url + ", To: " + redirect.LinkUrl);
        }

        public void Terminate()
        {

        }
    }
}
```

**Comment by abjerner** [comment]
Thanks again @prjseal 👍 

I've merged your changes now, but it currently lives in the [v2/dev/events](https://github.com/skybrud/Skybrud.Umbraco.Redirects/tree/v2/dev/events), so GitHub will not see it here before I merge the changes into the default branch.

I need to do some more testing before I merge it into the default branch. At @skybrud we primarily use Umbraco as a headless CMS, so requests then won't hit the HTTP module. So maybe we need to update the event logic to also support scenarios like this, which I need some more time looking into, and having a chat with my colleagues. I'm actually on vacation right now (looking through this PR as I'm watching Tour de France 😛), so it may not be until some time in August before I get around to this. 

Anyways, if we go back to the PR, I've changed your code a bit:

- **Updated HTTP module to only create a single instance of HttpContextBase (instead of one for each of the two events)** (see 49c8083757bc101d516f31b322873eaadab0fd9a)
Instead of creating a `HttpContextWrapper` for each of the two events, the HTTP module now initializes a `HttpContextWrapper` that is used for both events. Creating a new instance - especially since it's "just" a wrapper - may not be that expensive, but we'd might as well fix this.

- **Event should allow writing opposed to just reading** (see 2129bf7c1741504198423072aefddbbc23461221)
With your PR, the event logic only allows reading from the two events. Even if you do set another redirect from one of the events, the HTTP module didn't listen for this.

  Although I don't have a specific use case, I think the events should also allow writing as well, meaning that one can set a redirect from one of the events, and it will be reflected in the HTTP module. I've also changed the order of some of the lines to support this.

  So with my changes, if you set a redirect from the pre lookup event, the HTTP module will skip looking for redirects in the database, and it will skip the post lookup event (as the lookup isn't happening).

**Comment by prjseal** [comment]
Hi @abjerner, sorry I've not been on the project that was using this for a while. How are you getting on with this PR now. Is it ready to merge yet?

Paul

**Comment by abjerner** [comment]
Hi @prjseal 

I had a chat with my colleague, but I haven't had a look at it yet beyond that. I hope I will be able to look at this and push a new release with this some time next week, but I can't say for sure.

**Comment by abjerner** [comment]
Hi @prjseal 

I've now merged your changes into the `v2/latest` branch along with some of my own adjustments.

I settled on a solution where the package has the abstract [**RedirectPreLookupEventArgs**](https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/v2/latest/src/Skybrud.Umbraco.Redirects/Events/RedirectPreLookupEventArgs.cs) and [**RedirectPostLookupEventArgs**](https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/v2/latest/src/Skybrud.Umbraco.Redirects/Events/RedirectPostLookupEventArgs.cs) classes. These classes have properties for `Uri`, `RawUrl`, `QueryString` and then also `Redirect` - but no property for accessing the `HttpContextBase` of the incoming request.

But when using the package out of the box (via the HTTP module), the underlying types are actually [**RedirectPreLookupHttpContextEventArgs**](https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/v2/latest/src/Skybrud.Umbraco.Redirects/Events/RedirectPreLookupHttpContextEventArgs.cs) and [**RedirectPostLookupHttpContextEventArgs**](https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/v2/latest/src/Skybrud.Umbraco.Redirects/Events/RedirectPostLookupHttpContextEventArgs.cs) instead. Both do have a `HttpContext` property referencing a `HttpContextBase` for the current request.

This structure is to ensure the scenarios that I described earlier - eg. when we're using Umbraco as a headless CMS, where the HTTP module isn't hit.

**Pull request merged**
