### PR TITLE
Implement latest v2 migration into v3

### PR DESCRIPTION
**Pull request by rickbutterfield**
When trying to run the v3 NuGet package against a database that is being migrated from 8.17, the migration will fail as it is behind the v2 version. This fixes that issue by bringing over the `FixRootKeyValue` migration step.

Fixes issue #111

### CODE REVIEW

**Comment by rickbutterfield** [comment]
Merged in latest `v3/main` code from alpha006

**Comment by abjerner** [comment]
Hi @rickbutterfield 

I haven't had the time to look at your PR yet - or how migrating from Umbraco 8 to 9 works in general.

Could you possible describe the steps involved for testing this?

**Comment by rickbutterfield** [comment]
Hi @abjerner, of course!

- Set up an Umbraco 8.17 site running Redirects 2.1.0
- Duplicate the database
- Set up an Umbraco 9.x.x site running Redirects 3.0.0-alpha and point it at the duplicated database (I was running Umbraco 9.0.0-rc004 and Redirects 3.0.0-alpha005 when I found this issue but can also replicate with the latest version of both) 
- On startup, the error shown in #111 appears. This is because the 3.0.0-alpha migration steps end with `.To<RemoveIsRegexColumnMigration>("2.0.0-alpha002")` where as 2.1.0 ended with `.To<FixRootKeyValue>("2.0.5");` so it thinks it's trying to downgrade.

Hope that's helpful

**Comment by rickbutterfield** [comment]
Pulled the latest `v3/main` in

**Comment by abjerner** [comment]
@rickbutterfield thanks again for this PR and keeping the PR in sync with the main branch 👍 

I haven't been able to look at this yet, but hopefully I will soon 😉

**Comment by abjerner** [comment]
Hi @rickbutterfield 

I've had a lot of on my plate recently, so I haven't gotten around to this before now. I've now had some time to test and merge your PR 👍 

Both V2 and V3 have had some additional migrations since your PR, but I've updated the migration plan to account for this. When testing, it now works upgrading from `v2.1.3` to `v3.0.0-alpha008` 😍 

I'll see if I can push a new release either today or tomorrow 😉

**Pull request merged**
