### PR TITLE
#18 enables regular expression matching

### PR DESCRIPTION
**Pull request by skttl**
#18

### CODE REVIEW

**Comment by abjerner** [comment]
@skttl Thanks for creating the pull request. I have now had some time to look through your pull request, and hopefully I'll be able to merge it soon. There are some minor issues here and there, but otherwise it looks good 👍 

- By introducing the new `isRegex` parameter in the C# repository, you've changed the order of the parameters, which would then be a breaking change. There probably aren't many using the repository directly, but I'll probably have to change back the order of the parameters with the new one last.

- I think most editors won't have a clue about what regular expressions are, so the new option should probably be tugged a bit way. I'm still not totally sure how to show this yet, as I don't remember seeing something similar elsewhere in Umbraco. But right now I'm leaning towards something like shown in the mockup below. Any ideas? Maybe *Advanced options* should be collapsed by default? Maybe it should have it's own dialog/overlay?

image

**Comment by abjerner** [comment]
@skttl I've been looking a bit more through this pull request. Do you by any chance have some working examples? Because from what I can tell, the HTTP module will never find the correct redirect in the database as it just searches for the raw URL of the request, which won't match the inbound URL of a redirect using regex. Am I missing something?

**Comment by abjerner** [comment]
@skttl I've now merged your changes, but also outcommented some of it again due to the concerns I wrote about yesterday. Your feedback would be much appreciated - otherwise I'll save support for regex to later, and then I'll have a look at some of the other pull requests.

**Comment by skttl** [comment]
@abjerner I made a gif of the regex redirect working.

image

In the HttpModule this happens:
`
			var redirectUrl = redirect.LinkUrl;

			if (redirect.IsRegex)
			{
				var regex = new Regex(redirect.Url);

				if (_capturingGroupsRegex.IsMatch(redirectUrl))
				{
					redirectUrl = regex.Replace(redirect.Url, redirectUrl);
				}
			}`

So, if the redirect is a regex, and if the regex is matching. The redirect url get's changed to a regex replaced url.

**Comment by skttl** [comment]
Seems like github stops the animation. Here's a link https://www.dropbox.com/s/62xbcf8jxhdx9wt/2017-09-15_08-49-03.gif?dl=0

**Comment by abjerner** [comment]
I haven't used regular expressions in the 301 Url Tracker package before, and still have some problems understanding how to use this feature. Is it correct that I'm only able to use the `d` character to match one or more numbers, but not more advanced regex? Even something as simple as `/([0-9]+)` isn't matched.

A few more examples would be extremely helpful, as I'm feeling bad about adding a feature I don't know how is supposed to be used 👍

**Comment by Rann1** [comment]
@skttl Do you perhaps have an update for this? We'd love to use the regex feature ;-)

**Comment by skttl** [comment]
Just an update, I think you should be able to use any regex. If you'd like I can check what is maybe wrong. But as I commented on #18, I am no longer sure that this is something that should be in this package.

**Pull request merged**
