### PR TITLE
nuget web and dashboard transforms

### PR DESCRIPTION
**Pull request by Matthew-Wise**
Cant figure out how to link this to the issue :(

https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/31

### CODE REVIEW

**Comment by abjerner** [comment]
Thanks. I'll look into that 👍 

The manual configuration was actually a bit by design - but that was also back when this was just internal package. As more and more are using this package, it might be time to do this automatically - so thanks for creating the pull request.

**Comment by Matthew-Wise** [comment]
No worries, thanks for the great package! 
It is certainly an improvement the one I was using. 
Expect a couple more pull requests from me or a colleague to allow bulk imports, as it is something our SEO team requested, and I see no reason not to share.

**Comment by abjerner** [comment]
Awesome. There is actually already a feature request for bulk import: https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/27

If you or your colleagues are working on bulk import, feel free to use the thread for discussing the feature ;)

**Comment by Matthew-Wise** [comment]
Didn't spot it but will do.

**Comment by abjerner** [comment]
Hi @Matthew-Wise,

First of all sorry for taking so long to merge this PR. For a number of different reasons, I wasn't sure initially whether your changes were the right way to go.

For instance, dashboards configured via package.manifest were at some point scheduled for Umbraco 7.9. This would IMO have been a better solution than adding it to Dashboard.config. But then the package.manifest feature ended up being dropped for Umbraco 7, and it was eventually first supported in Umbraco 8.

Another reason was that the suggested transform would be wrong for some solutions - eg. if the dashboard should be available for all editors, and not just admins, or just generally that people would wish to configure it differently. For many of our solutions, we're using Umbraco as a headless CMS, so in these cases, we wouldn't add the HTTP module. Not having these transforms would in a way force developers to configure it to their own needs.

On the other hand, I guess most people would just want to go with configuration from your transforms. We had a chat about this at Skybrud, and came to the conclusion that your transforms were the right way to go (YAY!). We actually had this chat a while ago, but I probably didn't have the time to look into right away, and then ended forgetting about it (insert sad/shameful smiley here). Anyways, as I'm working on the Umbraco 8 version, I came across this PR again - which is why it has now *finally* been merged 👍 

A little side note: as you made the PR for the `master` branch (which is now the version for Umbraco 8), and I merged your changes into the `dev-v7` branch, GitHub apparently can't pickup that your changes was merged. I think that means I have to close the PR although it should of course has been marked as merged 🎉

The transforms for the HTTP module also makes sense for the Umbraco 8 version of this package, so I've cherry picked the the two files for the HTTP module transforms so the change is still attributed to you: https://github.com/skybrud/Skybrud.Umbraco.Redirects/commit/ed91a20eedd52377bd3026d604fbb20d30ee7544

The HTTP module has been renamed in the Umbraco 8 version, but I'll make sure to update the transforms to reflect that.

Thanks a lot for the work for this PR 👍 

tCV2LrPPYfqCY-robert-downet-jr

**Comment by Matthew-Wise** [comment]
Glad it was of use :D PR. No worries about the delay, we all get busy. Can't wait to be using V8 and your package again

**Pull request closed without merging**
