### PR TITLE
[gh88] handle other responses besides just 404

### PR DESCRIPTION
**Pull request by brendanmckenzie**
Resolves issue #88 by looking for responses other than just 404's.

### CODE REVIEW

**Review by abjerner — CHANGES_REQUESTED** [review]
Hi @brendanmckenzie 

Can you add a bit of description why this change is necessary?

Until I see some further details in #88, I believe that is a local issue unrelated to the redirects package.

**Comment by brendanmckenzie** [comment]
Hi @abjerner 

I found that with `customErrors` active (i.e., "On" or "RemoteOnly" for remote requests) the check that I changed where it was looking for status code 404 was receiving a 500 error in certain circumstances, typically when a file extension was supplied.

Looking for any non-successful HTTP response for the request, coupled with the redirect lookup seemed to be a decent solution and resolved the issue mentioned in the original ticket, along with the issue that I experienced that was almost identical to that.

The reason it might appear to be a local issue could be due to the use of "RemoteOnly" `customErrors` perhaps.  We only noticed this issue once we deployed it into our staging environment, locally it ran fine.

**Comment by abjerner** [comment]
@brendanmckenzie I tried reproducing it (locally) with different values for `customErrors`, but it still worked fine - which is why I'm inclined to believe it's a local or solution specific issue, and not a general one.

Nevertheless, when it does fail, are you able to see the exception somewhere? I stil haven't seen what the actual error is, so that would be helpful.

**Comment by KraftwerkWedl** [comment]
Maybe I can share some information that helps, hopefully.

I also had to track this error down in an azure web app. In my case it was a configuration mistake someone did, a bit nasty to find, nothing to do with this redirect package.

If you have StaticFileHandler configured for the media path as mentioned in that azure filesystem provider package:
https://our.umbraco.com/documentation/Extending/FileSystemProviders/Azure-Blob-Storage/

it handles /media paths like /media/xx/xx.pdf and throws an exception if the file does not exist:
`System.Web.HttpException (0x80004005): File does not exist.
	at System.Web.StaticFileHandler.ProcessRequestForNonMapPathBasedVirtualFile(HttpRequest request, HttpResponse response, String overrideVirtualPath)
	at System.Web.StaticFileHandler.ProcessRequestInternal(HttpContext context, String overrideVirtualPath)
	at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
	at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
	at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)`

https://github.com/microsoft/referencesource/blob/master/System.Web/StaticFileHandler.cs#L312
It is a http not found exception, which is actually quite fine.

The real issue was a configuration mistake in the customErrors section of the web.config.
`<customErrors mode="RemoteOnly" redirectMode="ResponseRewrite" defaultRedirect="/CustomError500.aspx"></customErrors>`

It is not triggered locally, but remote the CustomError500.aspx page is called on every http exception, rewriting the response:
`<% Response.StatusCode = 500; %>`

That is a problem, of course. So you should handle 404 errors as well with a custom error page:
`<customErrors mode="RemoteOnly" redirectMode="ResponseRewrite" defaultRedirect="/CustomError500.aspx">
  <error statusCode="404" redirect="/CustomError404.aspx" />
</customErrors>`

rewriting the respone:
`<% Response.StatusCode = 404; %>`

That will give the RedirectsModule a chance to kick in.

**Comment by abjerner** [comment]
Thanks for the @brendanmckenzie and @KraftwerkWedl 

As the conclusion seems to be that this is not an issue with this package, I'm closing the PR.

**Pull request closed without merging**
